services:
  - type: web
    name: trunklink-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VAPID_SUBJECT
        value: mailto:support@trunklink.com
      - key: VAPID_PUBLIC_KEY
        value: BIGFGakKm1X-Y3vW5wkUf7T5l8M5lIxHQBtGmrkBzDQXbCsQiX0zSXUPBTdeL9a-D31iSz63exZ8j1oXOsA_w1Q
      - key: VAPID_PRIVATE_KEY
        value: t-Ub8ywR18KjomdyDcgCiuXa39tVGYIO2IDHWG-RqL0
      - key: FIREBASE_PROJECT_ID
        value: geofence-5bdcc
      - key: FIREBASE_DATABASE_URL
        value: https://geofence-5bdcc-default-rtdb.firebaseio.com