services:
  - type: web
    name: trunklink-web
    runtime: static
    staticPublishPath: ./
    buildCommand: echo "No build required for static site"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), camera=(), microphone=()
    routes:
      - type: rewrite
        source: /*
        destination: /public-alerts.html